### ISSUE TITLE
Fix error in TRC with units

### ISSUE THREAD

**Issue by ElineSchaft** [UMCU-EpiLAB/umcuEpi_acute_ieeg_respect_bids#9]
Now fixed in lines 162-163 of read_micromed_trc.m

**Comment by PauluzzS** [comment]
Measurement unit uint 102 should represent dimensionless quantities ("Adim.")
TRC files without any unit seems out of the specification of the TRC file format. We should check the bytes in the trc header to understand how this is converted to an empty double.

**Comment by PauluzzS** [comment]
> The offset -1 (one back) makes the function read the _status byte_ as _type byte_, and subsequently the _type byte_ as first character of the electrode name. Hence a leading blank character in G2-referenced electrode names and a leading weird character in bipolar electrode names. This ultimately shifts the last byte of the _PhysMax_ long to be interpreted as the first unit byte, causing unspecified unit representations to occur (e.g. 26112).

Should remove in external/read_micromed_trc.m
`133	    fseek(fid,-1,0);`
